### ISSUE TITLE
A suggestion to drop lodash.clonedeep in favour of structuredClone

### ISSUE THREAD

**Issue by StefanNedelchev** [cornerstonejs/cornerstone3D-beta#503]
When I import `@cornerstonejs/core` into an Angular project and try to build it I get the following warning:
![image](https://user-images.githubusercontent.com/15238282/226997571-237991ea-adae-452f-91e0-4621864fa4af.png)

This is a common warning that appears if pretty much any lodash feature is used (or other commonjs dependencies) and [there is a good reason behind](https://angular.io/guide/build#configuring-commonjs-dependencies). But even if we put Angular aside, it's always a good thing if we can get rid of 3rd party packages when there is an opportunity. Since Cornerstone 3D is meant to be for modern browsers anyway, we could use the [structuredClone()](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone) method for deep cloning of objects instead of relying on `lodash.clonedeep()`. The function is supported by pretty much every modern desktop and web browser with the exception that it's not available in workers on Opera and Safari.

**Comment by sedghi** [comment]
Yes indeed, I prefer structuredClone as well, if you can create a PR I would be happy to review and merge

**Comment by StefanNedelchev** [comment]
@sedghi I created a PR. Although the builds and tests passed locally, the tests here failed. From the logs I see there is one of the errors:

```
 An error was thrown in afterAll
  DataCloneError: Failed to execute 'structuredClone' on 'Window': SVGCircleElement object could not be cloned.
  error properties: Object({ code: 25, INDEX_SIZE_ERR: 1, DOMSTRING_SIZE_ERR: 2, HIERARCHY_REQUEST_ERR: 3, WRONG_DOCUMENT_ERR: 4, INVALID_CHARACTER_ERR: 5, NO_DATA_ALLOWED_ERR: 6, NO_MODIFICATION_ALLOWED_ERR: 7, NOT_FOUND_ERR: 8, NOT_SUPPORTED_ERR: 9, INUSE_ATTRIBUTE_ERR: 10, INVALID_STATE_ERR: 11, SYNTAX_ERR: 12, INVALID_MODIFICATION_ERR: 13, NAMESPACE_ERR: 14, INVALID_ACCESS_ERR: 15, VALIDATION_ERR: 16, TYPE_MISMATCH_ERR: 17, SECURITY_ERR: 18, NETWORK_ERR: 19, ABORT_ERR: 20, URL_MISMATCH_ERR: 21, QUOTA_EXCEEDED_ERR: 22, TIMEOUT_ERR: 23, INVALID_NODE_TYPE_ERR: 24, DATA_CLONE_ERR: 25 })
  Error: Failed to execute 'structuredClone' on 'Window': SVGCircleElement object could not be cloned.
      at resetCornerstoneToolsState (webpack-internal:///./packages/tools/src/store/state.ts:8:4094)
      at Module.destroy (webpack-internal:///./packages/tools/src/init.ts:21:14870)
      at UserContext.eval (webpack-internal:///./packages/tools/test/FrameOfReferenceSpecificToolStateManager_test.js:56:45)
      at <Jasmine>
```
I double checked the MDN docs for structuredClone() and by looking at [supported types](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm#supported_types) it seems that HTML and SVG elements are not present. A quick test in the a JS console confirmed that:
![image](https://user-images.githubusercontent.com/15238282/227643557-0efa4bf8-8fca-44a0-a389-4d1b01e6c197.png)

I'm leaving the draft PR open in case if anyone wants to investigate different solutions to these cases.

**Comment by StefanNedelchev** [comment]
@sedghi maybe we can close this since #517 has been merged?
